2025/02/20 13:26:31 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/online-users/ HTTP/1.1", upstream: "http://172.18.0.6:8000/api/users/online-users/", host: "localhost:8080", referrer: "http://localhost:8080/"
2025/02/24 11:41:09 [error] 8#8: *724 client intended to send too large body: 1193066 bytes, client: 172.18.0.1, server: localhost, request: "PUT /api/users/profile/ HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2025/02/24 17:44:43 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/online-users/ HTTP/1.1", upstream: "http://172.18.0.6:8000/api/users/online-users/", host: "localhost:8080", referrer: "http://localhost:8080/"
2025/02/25 14:13:10 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/online-users/ HTTP/1.1", upstream: "http://172.18.0.6:8000/api/users/online-users/", host: "localhost:8080", referrer: "http://localhost:8080/"
